version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "teste123"
      MYSQL_DATABASE: "communitydb"
    ports:
      - "3306:3306"
    volumes:
      - /home/paula/Documentos/repositorios/openCommunity/mysql:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge
